server {
    listen 80;
    server_name _;

    add_header Access-Control-Allow-Origin "*" always;
    add_header Access-Control-Allow-Methods "GET,HEAD,OPTIONS" always;
    add_header Access-Control-Allow-Headers "*" always;

    location = /health {
        add_header Content-Type text/plain;
        return 200 'ok';
    }

    location / {
        root /var/www/dash;
        try_files $uri $uri/ =404;
    }

    types {
        application/dash+xml mpd;
        video/iso.segment m4s;
        video/mp4 mp4;
    }
}
